### ISSUE TITLE
Investigate the performance impact of CUDA managed memory

### ISSUE THREAD

**Issue by makortel** [cms-patatrack/pixeltrack-standalone#43]
I'm thinking to make a full version of `cuda` program that uses the CUDA managed memory (kind of follow-up to https://github.com/cms-patatrack/cmssw/issues/85). The question of the performance impact seems to affect both the portability technology exploration and the evolution of the CUDA products in EDM, so maybe it is time to make a proper evaluation.

Plan
- [x] Clone `cuda` to `cudauvm` done in #44 
- [x] Clone `CachingHostAllocator` to `CachingManagedAllocator`, create `cms::managed::unique_ptr` done in #49 
- [x] Migrate conditions done in #53 
- [x] Migrate beamspot transfer done in #54
- [x] Migrate raw-to-cluster done in #123 
- [x] Migrate rechits done in #162
- [x] Migrate CA done in #182 
- [x] Migrate vertexing done in #182
- [x] Evaluate performance, at least on T4 and V100

I'm thinking to have compile-time switches to
* enable/disable `cudaMemPrefetchAsync()`
* use device/managed memory for (temporary) device-only data structures

**Comment by makortel** [comment]
The evaluation was reported in vCHEP 2021
